### ISSUE TITLE
Issue on small datasets

### ISSUE THREAD

**Issue by nuzrub** [tsc2017/Frechet-Inception-Distance#4]
Hi, I just wanted to let you know I found a minor bug when using datasets that are smaller than the batch size. When this happens, the integer division evaluates to zero and no batch is computed whatsoever. With no values computed, no FID is given, resulting in a NaN output.

The fix is pretty simple and is basically: 
n_batches = Max(1, inps.shape[0]//BATCH_SIZE)

At line 52.

**Comment by tsc2017** [comment]
Hi, this bug is now fixed. Now the code can utilize the entire inputs. 
Note that one should be cautious of small samples as the extimators of the means and variances can have high variance.
Also see Issue #1.
